### ISSUE TITLE
Unknown error 

### ISSUE THREAD

**Issue by sakshamece** [tejgop/nginx-module-guide#3]
/Library/Developer/CommandLineTools/usr/bin/make -f objs/Makefile install
cc -c -fPIC -pipe  -O -Wall -Wextra -Wpointer-arith -Wconditional-uninitialized -Wno-unused-parameter -Wno-deprecated-declarations -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules \
		-o objs/addon/ngx_http_hello_world_module/ngx_http_hello_world_module.o \
		/Users/sakshams/Downloads/nginx-1.16.1/src/ngx_http_hello_world_module/ngx_http_hello_world_module.c
cc -o objs/ngx_http_hello_world_module.so \
	objs/addon/ngx_http_hello_world_module/ngx_http_hello_world_module.o \
	objs/ngx_http_hello_world_module_modules.o \
	-shared -Wl,-undefined,dynamic_lookup
test -d '/Users/sakshams/Downloads/nginx-1.16.1' || mkdir -p '/Users/sakshams/Downloads/nginx-1.16.1'
test -d '/Users/sakshams/Downloads/nginx-1.16.1/sbin' \
		|| mkdir -p '/Users/sakshams/Downloads/nginx-1.16.1/sbin'
test ! -f '/Users/sakshams/Downloads/nginx-1.16.1/sbin/nginx' \
		|| mv '/Users/sakshams/Downloads/nginx-1.16.1/sbin/nginx' \
			'/Users/sakshams/Downloads/nginx-1.16.1/sbin/nginx.old'
cp objs/nginx '/Users/sakshams/Downloads/nginx-1.16.1/sbin/nginx'
test -d '/Users/sakshams/Downloads/nginx-1.16.1/conf' \
		|| mkdir -p '/Users/sakshams/Downloads/nginx-1.16.1/conf'
cp conf/koi-win '/Users/sakshams/Downloads/nginx-1.16.1/conf'
cp: /Users/sakshams/Downloads/nginx-1.16.1/conf/koi-win and conf/koi-win are identical (not copied).
make[1]: *** [install] Error 1
make: *** [install] Error 2

**Comment by tejgop** [comment]
I'm not able to reproduce this error. Is it resolved? What is your setup?

**Comment by sakshamece** [comment]
@tejgop  yes it is resolved , i am using vagrant setup
